#!/usr/bin/env bash

# Use: wrapperctl <install|uninstall> [options] <command> <new_command>
# Example: wrapperctl install -s -si -a pacman brumba
#          wrapperctl uninstall brumba

help() {
  echo "Script for creating wrapper commands on Linux"
  echo
  echo "Usage:"
  echo "  wrapperctl install [options] <command> <new_command>"
  echo "  wrapperctl uninstall <wrapper_name>"
  echo "  wrapperctl list"
  echo
  echo "Commands:"
  echo "  install     Install a new wrapper"
  echo "  uninstall   Remove an existing wrapper"
  echo "  list        List installed wrappers"
  echo
  echo "Options for install:"
  echo "  -s    Use sudo inside wrapper command"
  echo "  -si   Use sudo for installation"
  echo "  -a    Install for all users (/usr/local/bin)"
  echo "  -h    Show this help"
  exit 0
}

show_install_help() {
  echo "Usage: wrapperctl install [options] <command> <new_command>"
  echo
  echo "Options:"
  echo "  -s    Use sudo inside wrapper command"
  echo "  -si   Use sudo for installation"
  echo "  -a    Install for all users (/usr/local/bin)"
  echo "  -h    Show this help"
  exit 0
}

show_uninstall_help() {
  echo "Usage: wrapperctl uninstall <wrapper_name>"
  echo
  echo "This command removes a wrapper from the system."
  echo "If installed system-wide with -a, use sudo for uninstall."
  exit 0
}

# Defaults
WRAP_SUDO=""
INSTALL_SUDO=""
INSTALL_DIR="$HOME/.local/bin"
COMMAND=""
NEW_COMMAND=""
ACTION=""

# Check if at least one argument is provided
if [[ $# -eq 0 ]]; then
  help
fi

# Parse action
case "$1" in
install | i)
  ACTION="install"
  shift
  ;;
uninstall | remove | rm | u)
  ACTION="uninstall"
  shift
  ;;
list | ls)
  ACTION="list"
  shift
  ;;
-h | --help | help)
  help
  ;;
*)
  echo "[ERROR]: Unknown action: $1"
  echo "Use 'install', 'uninstall', or 'list'"
  exit 1
  ;;
esac

install_wrapper() {
  # Parse install arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
    -s)
      WRAP_SUDO="sudo"
      shift
      ;;
    -si)
      INSTALL_SUDO="sudo"
      shift
      ;;
    -a)
      INSTALL_DIR="/usr/local/bin"
      shift
      ;;
    -h | --help)
      show_install_help
      ;;
    *)
      if [[ -z "$COMMAND" ]]; then
        COMMAND="$1"
      elif [[ -z "$NEW_COMMAND" ]]; then
        NEW_COMMAND="$1"
      else
        echo "[ERROR]: Too many arguments"
        show_install_help
      fi
      shift
      ;;
    esac
  done

  # Check required arguments
  if [[ -z "$COMMAND" || -z "$NEW_COMMAND" ]]; then
    echo "[ERROR]: Missing required arguments"
    echo "Need both <command> and <new_command> for installation"
    show_install_help
  fi

  # Check that wrapped command exists
  if ! command -v "$COMMAND" &>/dev/null; then
    echo "[ERROR]: Command '$COMMAND' not found"
    exit 1
  fi

  # Check if target command already exists
  if command -v "$NEW_COMMAND" &>/dev/null; then
    echo "[WARNING]: Command '$NEW_COMMAND' already exists"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 1
    fi
  fi

  # Create temp file
  TEMPLATE="$(mktemp)"
  trap 'rm -f "$TEMPLATE"' EXIT

  # Create wrapper script
  cat <<EOF >"$TEMPLATE"
#!/usr/bin/env bash
# Wrapper for $COMMAND
# Generated by wrapper script

if [[ -n "$WRAP_SUDO" ]]; then
  exec sudo $COMMAND "\$@"
else
  exec $COMMAND "\$@"
fi
EOF

  chmod 755 "$TEMPLATE"

  # Ensure install directory exists
  if [[ ! -d "$INSTALL_DIR" ]]; then
    echo "[INFO]: Creating $INSTALL_DIR"
    $INSTALL_SUDO mkdir -p "$INSTALL_DIR" || exit 1
  fi

  # Install wrapper
  echo "[INFO]: Installing '$NEW_COMMAND' to $INSTALL_DIR"
  $INSTALL_SUDO cp "$TEMPLATE" "$INSTALL_DIR/$NEW_COMMAND" &&
    $INSTALL_SUDO chmod 755 "$INSTALL_DIR/$NEW_COMMAND"

  # Final status
  if [[ $? -eq 0 ]]; then
    echo "[SUCCESS]: Wrapper '$NEW_COMMAND' for '$COMMAND' installed"
    echo "Run with: $NEW_COMMAND"
  else
    echo "[ERROR]: Installation failed"
    exit 1
  fi
}

uninstall_wrapper() {
  local wrapper_name=""
  local use_sudo=""

  # Parse uninstall arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
    -h | --help)
      show_uninstall_help
      ;;
    -*)
      echo "[ERROR]: Unknown option: $1"
      show_uninstall_help
      ;;
    *)
      if [[ -z "$wrapper_name" ]]; then
        wrapper_name="$1"
      else
        echo "[ERROR]: Too many arguments for uninstall"
        show_uninstall_help
      fi
      shift
      ;;
    esac
  done

  # Check required argument
  if [[ -z "$wrapper_name" ]]; then
    echo "[ERROR]: Missing wrapper name"
    show_uninstall_help
  fi

  # Try to find the wrapper in common locations
  local wrapper_path=""

  # Check system-wide first
  if [[ -f "/usr/local/bin/$wrapper_name" ]]; then
    wrapper_path="/usr/local/bin/$wrapper_name"
    use_sudo="sudo"
  elif [[ -f "/usr/bin/$wrapper_name" ]]; then
    wrapper_path="/usr/bin/$wrapper_name"
    use_sudo="sudo"
  elif [[ -f "$HOME/.local/bin/$wrapper_name" ]]; then
    wrapper_path="$HOME/.local/bin/$wrapper_name"
  fi

  if [[ -z "$wrapper_path" ]]; then
    # Check if it's in PATH
    if command -v "$wrapper_name" &>/dev/null; then
      wrapper_path="$(command -v "$wrapper_name")"
      # Determine if sudo is needed based on directory
      if [[ "$wrapper_path" == /usr/* ]]; then
        use_sudo="sudo"
      fi
    else
      echo "[ERROR]: Wrapper '$wrapper_name' not found"
      exit 1
    fi
  fi

  # Check if it's actually a wrapper script
  if ! grep -q "Generated by wrapper script" "$wrapper_path" 2>/dev/null; then
    echo "[WARNING]: '$wrapper_path' doesn't appear to be a wrapper script"
    read -p "Remove anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 1
    fi
  fi

  # Remove the wrapper
  echo "[INFO]: Removing wrapper '$wrapper_name' from $wrapper_path"
  $use_sudo rm -f "$wrapper_path"

  if [[ $? -eq 0 ]]; then
    echo "[SUCCESS]: Wrapper '$wrapper_name' removed"
  else
    echo "[ERROR]: Failed to remove wrapper"
    exit 1
  fi
}

list_wrappers() {
  echo "Installed wrappers:"
  echo "==================="

  # Check common installation directories
  local dirs=("$HOME/.local/bin" "/usr/local/bin" "/usr/bin")
  local found=0

  for dir in "${dirs[@]}"; do
    if [[ -d "$dir" ]]; then
      echo ""
      echo "Checking $dir:"
      for file in "$dir"/*; do
        if [[ -f "$file" ]] && grep -q "Generated by wrapper script" "$file" 2>/dev/null; then
          # Extract wrapped command from the file
          local wrapped_cmd=$(grep "^# Wrapper for " "$file" | head -1 | cut -d' ' -f4-)
          echo "  $(basename "$file") -> $wrapped_cmd"
          found=1
        fi
      done
    fi
  done

  if [[ $found -eq 0 ]]; then
    echo "No wrappers found."
  fi
}

# Execute based on action
case "$ACTION" in
install)
  install_wrapper "$@"
  ;;
uninstall)
  uninstall_wrapper "$@"
  ;;
list)
  list_wrappers "$@"
  ;;
esac
